export interface barDataI {
  // "id":string,
  // 'profite':number,
  // "loss":number,
  // "country":string,
  // "value":number,
  // 'sector':string,
  // 'intensity':number,
  
  "_id": string,
  "end_year": string,
  "intensity": number,
  "sector": string,
  "topic": string,
  "insight": string,
  "url":string,
  "region": string,
  "start_year": string,
  "impact": string,
  "added": string,
  "published": string,
  "country": string,
  "relevance": number,
  "pestle": string,
  "source":string,
  "title": string,
  "likelihood": number,
  "__v": number
  }