import { barDataI } from "./chartinterface";
export const barData:barDataI[]=
[
    {
        "_id": "64ee2a0ed058c6b8898481b0",
        "end_year": "",
        "intensity": 6,
        "sector": "Energy",
        "topic": "gas",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
        "start_year": "",
        "impact": "",
        "added": "January, 20 2017 03:51:25",
        "published": "January, 09 2017 00:00:00",
        "country": "United States of America",
        "relevance": 2,
        "pestle": "Industries",
        "source": "EIA",
        "title": "U.S. natural gas consumption is expected to increase during much of the projection period.",
        "likelihood": 3,
        "__v": 0
    },
    {
        "_id": "64ee2af8edfc0aeb6fc285e0",
        "end_year": "",
        "intensity": 6,
        "sector": "Energy",
        "topic": "oil",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
        "start_year": "",
        "impact": "",
        "added": "January, 20 2017 03:51:24",
        "published": "January, 09 2017 00:00:00",
        "country": "United States of America",
        "relevance": 2,
        "pestle": "Industries",
        "source": "EIA",
        "title": "Reference case U.S. crude oil production is projected to recover from recent declines.",
        "likelihood": 3,
        "__v": 0
    },
    {
        "_id": "64ee2af8edfc0aeb6fc285e1",
        "end_year": "",
        "intensity": 6,
        "sector": "Energy",
        "topic": "consumption",
        "insight": "Annual Energy Outlook",
        "url": "http://www.eia.gov/outlooks/aeo/pdf/0383(2017).pdf",
        "region": "Northern America",
        "start_year": "",
        "impact": "",
        "added": "January, 20 2017 03:51:23",
        "published": "January, 09 2017 00:00:00",
        "country": "United States of America",
        "relevance": 2,
        "pestle": "Industries",
        "source": "EIA",
        "title": "U.S. petroleum consumption is projected to remain below the 2005 level.",
        "likelihood": 3,
        "__v": 0
    },
    {
        "_id": "64ee2c52edfc0aeb6fc285e4",
        "end_year": "",
        "intensity": 6,
        "sector": "Environment",
        "topic": "oil",
        "insight": "WRI Partnership Aims to Foster Supply Chain Transparency, Zero-Deforestation Strategies",
        "url": "http://www.sustainablebrands.com/news_and_views/supply_chain/sustainable_brands/wri_partnership_aims_foster_supply_chain_transparency",
        "region": "Central America",
        "start_year": "",
        "impact": "",
        "added": "January, 20 2017 03:26:40",
        "published": "January, 18 2017 00:00:00",
        "country": "Mexico",
        "relevance": 3,
        "pestle": "Environmental",
        "source": "sustainablebrands.com",
        "title": "Mars, Unilever, Cargill and Mondelēz are already using GFW Commodities to assess deforestation risks in their palm oil, soy and cocoa supply chains across a collective area of land the size of Mexico.",
        "likelihood": 2,
        "__v": 0
    },
    {
        "_id": "64ee2c52edfc0aeb6fc285e5",
        "end_year": "",
        "intensity": 6,
        "sector": "",
        "topic": "market",
        "insight": "N-Hexane Market Hit at a CAGR of 5% by 2024 - PMR Report",
        "url": "http://www.sbwire.com/press-releases/n-hexane-market-hit-at-a-cagr-of-5-by-2024-pmr-report-761520.htm",
        "region": "World",
        "start_year": "",
        "impact": "",
        "added": "January, 19 2017 00:55:54",
        "published": "January, 18 2017 00:00:00",
        "country": "",
        "relevance": 2,
        "pestle": "Economic",
        "source": "SBWire",
        "title": "Polymerization will remain top 3 end-users in global n-Hexane Market.",
        "likelihood": 3,
        "__v": 0
    },
    {
        "_id": "64ee2c52edfc0aeb6fc285e6",
        "end_year": "",
        "intensity": 6,
        "sector": "Energy",
        "topic": "oil",
        "insight": "N-Hexane Market Hit at a CAGR of 5% by 2024 - PMR Report",
        "url": "http://www.sbwire.com/press-releases/n-hexane-market-hit-at-a-cagr-of-5-by-2024-pmr-report-761520.htm",
        "region": "World",
        "start_year": "",
        "impact": "",
        "added": "January, 19 2017 00:55:52",
        "published": "January, 18 2017 00:00:00",
        "country": "",
        "relevance": 2,
        "pestle": "Economic",
        "source": "SBWire",
        "title": "High demand for n-Hexane in oil extraction owing to its effectiveness and high yield is expected to propel the global n-Hexane Market.",
        "likelihood": 3,
        "__v": 0
    },
    {
        "_id": "64ee2c52edfc0aeb6fc285e7",
        "end_year": "2027",
        "intensity": 60,
        "sector": "Government",
        "topic": "market",
        "insight": "E-Boats, Anyone? Electric Boat Market To Reach $20 Billion By 2027, According To New Study",
        "url": "https://cleantechnica.com/2017/01/12/e-boats-anyone-electric-boat-market-reach-20b-2027-according-new-study/",
        "region": "",
        "start_year": "",
        "impact": "3",
        "added": "January, 18 2017 02:23:13",
        "published": "January, 13 2017 00:00:00",
        "country": "",
        "relevance": 5,
        "pestle": "Political",
        "source": "CleanTechnica",
        "title": "The market for non-military electric watercraft and marine motors will balloon to over $20 billion worldwide by 2027.",
        "likelihood": 4,
        "__v": 0
    },
    {
        "_id": "64ee2c52edfc0aeb6fc285e8",
        "end_year": "2018",
        "intensity": 16,
        "sector": "Energy",
        "topic": "oil",
        "insight": "Oil prices will be much more volatile in 2017",
        "url": "http://www.news.tracanada.ca/2017/01/16/oil-prices-will-be-much-more-volatile-in-2017/",
        "region": "World",
        "start_year": "2017",
        "impact": "",
        "added": "January, 17 2017 04:19:59",
        "published": "January, 16 2017 00:00:00",
        "country": "",
        "relevance": 4,
        "pestle": "Economic",
        "source": "TRAC News",
        "title": "Global oil prices will witness much more volatility in 2017 even though markets may rebalance in the first half of the year if output cuts pledged by producers are implemented.",
        "likelihood": 4,
        "__v": 0
    },
    {
        "_id": "64ee2c52edfc0aeb6fc285e9",
        "end_year": "2018",
        "intensity": 16,
        "sector": "",
        "topic": "gdp",
        "insight": "IMF affirms Nigeria's recovery from recession, with 0.8% growth forecast",
        "url": "http://www.vanguardngr.com/2017/01/imf-affirms-nigerias-recovery-recession-0-8-growth-forecast/",
        "region": "Western Africa",
        "start_year": "2017",
        "impact": "",
        "added": "January, 17 2017 03:25:45",
        "published": "January, 16 2017 00:00:00",
        "country": "Nigeria",
        "relevance": 4,
        "pestle": "Economic",
        "source": "Vanguard News",
        "title": "Nigeria Gross Domestic Product will grow by 0.8 percent in 2017 and 2.3 percent in 2018.",
        "likelihood": 4,
        "__v": 0
    },
    {
        "_id": "64ee2c52edfc0aeb6fc285ea",
        "end_year": "",
        "intensity": 6,
        "sector": "Aerospace & defence",
        "topic": "war",
        "insight": "Lebanon: No Land for Beginning Politicians",
        "url": "https://www.avimelamed.com/2017/01/07/lebanon-no-land-for-beginning-politicians/",
        "region": "Western Asia",
        "start_year": "",
        "impact": "",
        "added": "January, 17 2017 03:18:22",
        "published": "January, 07 2017 00:00:00",
        "country": "Lebanon",
        "relevance": 2,
        "pestle": "Political",
        "source": "Avi Melamed",
        "title": "A war in Lebanon will increase the already heavy economic burden Saudi Arabia is carrying.",
        "likelihood": 3,
        "__v": 0
    }
]